# Generated by Django 5.0.6 on 2024-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
    ]
