# Generated by Django 5.0.6 on 2024-06-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassmodel',
            name='courses',
        ),
        migrations.AddField(
            model_name='studentclassmodel',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='class_app.coursesmodel'),
        ),
    ]
